# Generated by Django 5.1.2 on 2024-11-01 15:34

import companies.validations.cnpj_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='cnpj',
            field=models.CharField(max_length=150, validators=[companies.validations.cnpj_validator.validate_cnpj], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='number',
            field=models.IntegerField(verbose_name='Numero'),
        ),
    ]
